import sqlite3
from tkinter import *
from tkinter import messagebox
parent=Tk()
def add():
    bra=br.get()
    na=nam.get()
    co=col.get()
    raa=ra.get()
    roo=ro.get()
    ca=cam.get()
    pr=pro.get()
    ba=bat.get()
    am=amo.get()
    qt=int(qty.get())
    conn=sqlite3.connect("ss.db")
    cursor=conn.cursor()
    cursor.execute("insert into addmobile(br,nam,col,ra,ro,cam,pro,bat,amo,qty)values(?,?,?,?,?,?,?,?,?,?)",(bra,na,co,raa,roo,ca,pr,ba,am,qt))
    conn.commit()
    print("records inserted....")
    conn.close()
brand=Label(parent,text="Brand").grid(row=0,column=0)
br=Entry(parent)
br.grid(row=0,column=1) 
name=Label(parent,text="Name").grid(row=1,column=0)
nam=Entry(parent)
nam.grid(row=1,column=1)
colour=Label(parent,text="colour").grid(row=2,column=0)
col=Entry(parent)
col.grid(row=2,column=1)
ram=Label(parent,text="RAM").grid(row=3,column=0)
ra=Entry(parent)
ra.grid(row=3,column=1)
rom=Label(parent,text="ROM").grid(row=4,column=0)
ro=Entry(parent)
ro.grid(row=4,column=1)
camera=Label(parent,text="Camera").grid(row=5,column=0)
cam=Entry(parent)
cam.grid(row=5,column=1)
processor=Label(parent,text="processor").grid(row=6,column=0)
pro=Entry(parent)
pro.grid(row=6,column=1)
battery=Label(parent,text="Battery").grid(row=7,column=0)
bat=Entry(parent)
bat.grid(row=7,column=1)
display=Label(parent,text="display").grid(row=8,column=0)
dis=Entry(parent)
dis.grid(row=8,column=1)
amount=Label(parent,text="Amount").grid(row=9,column=0)
amo=Entry(parent)
amo.grid(row=9,column=1)
quantity=Label(parent,text="quantity").grid(row=10,column=0)
qty=Entry(parent)
qty.grid(row=10,column=1)
b1=Button(parent,text="submit",command=add).grid(row=12,column=1)
def can():
    parent.destroy()
    import logincr
b2=Button(parent,text="cancel").grid(row=12,column=0)
parent.mainloop()
