import sqlite3
from tkinter import *
from tkinter import messagebox
parent=Tk()
def adddet():
   
    nm=na.get()
    nmb=num.get()
    add=ads.get()
    bra=br.get()
    brn=bna.get()
    raa=ra.get()
    roo=ro.get()
    am=int(amo.get())
    qt=int(qty.get())
    conn=sqlite3.connect("ss.db")
    cursor=conn.cursor()
    cursor.execute('select qty from ADDMOBILE where br=?',(bra,))
    result=cursor.fetchall()
    for row in result:
        print(result)
        qtyy=int(row[0])
        print(qtyy)
    qtyy=qtyy-qt
    print(qtyy)
    cursor.execute("update ADDMOBILE set qty=? where br=?",(qtyy,bra))                  
    conn.commit()
    cursor.execute("insert into SALE(na,num,ads,br,bna,ra,ro,amo,qty)values(?,?,?,?,?,?,?,?,?)",(nm,nmb,add,bra,brn,raa,roo,am,qt))
    conn.commit()
    
    conn.close()
   
    
    print("records sale....")
nm=Label(parent,text="name").grid(row=0,column=0)
na=Entry(parent)
na.grid(row=0,column=1)
number=Label(parent,text="number").grid(row=1,column=0)
num=Entry(parent)
num.grid(row=1,column=1)
address=Label(parent,text="address").grid(row=2,column=0)
ads=Entry(parent)
ads.grid(row=2,column=1)
brand=Label(parent,text="Brand").grid(row=3,column=0)
br=Entry(parent)
br.grid(row=3,column=1) 
name=Label(parent,text="Name").grid(row=4,column=0)
bna=Entry(parent)
bna.grid(row=4,column=1)
ram=Label(parent,text="RAM").grid(row=5,column=0)
ra=Entry(parent)
ra.grid(row=5,column=1)
rom=Label(parent,text="ROM").grid(row=6,column=0)
ro=Entry(parent)
ro.grid(row=6,column=1)
amount=Label(parent,text="Amount").grid(row=7,column=0)
amo=Entry(parent)
amo.grid(row=7,column=1)
quantity=Label(parent,text="quantity").grid(row=8,column=0)
qty=Entry(parent)
qty.grid(row=8,column=1)
b1=Button(parent,text="sale",command=adddet).grid(row=10,column=1)
b2=Button(parent,text="cancel").grid(row=10,column=0)
parent.mainloop()
